# Programming-for-DataAnalysis
### Practical Assignment for Semester 2 - 2019
#### Student Name : Sasikala Varatharajan
#### Student Number : G00376470

### Assignment Topic : numpy.random package in Python


##  1. Explain the overall purpose of the package

NumPy is the fundamental package for scientific computing with Python. It provides:

 - a powerful N-dimensional array object

 - sophisticated (broadcasting) functions

 - tools for integrating C/C++ and Fortran code

 - useful linear algebra, Fourier transform, and random number capabilities

On the top of it's scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined and this allows NumPy to speedily integrate with a wide variety of databases.

Numpy is a specialist package that is really efficient dealing with arrays and numbers. It is used to perform different operations. It is a multidimensional array used to store values of same datatypes. It uses much less memory to store data. It takes significantly less amount of memory as compared to python lists. It provie a significant number of additional benefits which makes it easy to apply mathemical calculations.

Numpy.random is a sub-package of the numpy package in Python and it is used to generate random (pseudorandom) numbers. A number of other packages depend on Numpy. Interacting with it directly is not that common - You usually interact with numpy objects through the use of other packages such as pandas or scipy. There are a number of ways to generate random numbers and the numpy.random package has four sections to do this:

1 - Random Data Sampling

2 - Permutations

3 - Distributions - different probability distributions

4 - Random Generator

### 1.1  Importing the libaries for this project: Numpy, Matplotlib, Pandas and Seaborn

NumPy is the fundamental package for scientific computing with Python

Matplotlib ss a Pythod 2D plotting library for the Python programming language and its numerical mathematics extension NumPy.

Pandas is an open source, BSD-licensed library providing high-performance, easy-to-use data structures and data analysis tools.

Seaborn is a Python visualization library based on matplotlib. It provides a high-level interface for drawing attractive statistical graphics.

In [1]:
# import numpy
import numpy as np
# import matplotlib
import matplotlib.pyplot as plt
# import pandas
import pandas as pd
# import seaborn
import seaborn as sns

## 2. Explian the use of the "Simple random data" and "Permutations" functions

### 2.1 Simple Random Data

A research on a large set of data is time consuming and most of the time researchers use to choose a sample data from the large set of data to do their research. 

All the functions under Simple random data section is doing the same to generate a simple set of random data. The output from the functions are always in a simple structure like one random number, integers only, array of numbers in a 2 x 2 array, numbers in a specific format between the selected range, etc. Now a days a number of gamming apps are using the same technique to suffle the values. 

I have included few functions from Simple Random data section of numpy.random to show how it is used in Python programming with examples.


#### 2.1.1 - np.random.rand

np.random.rand retuns values in a given shape. It will create an array of the given shape and populate it with random sample from a uniform distribution over [0, 1] 

The dimentions of the returned array, should all be positive. If no arguments is given a single Pythod float is returned.

The example below will return an array with 3 columns and 4 rows with numbers betweeen 0 and 1

In [2]:
## Generate a 4 X 3 random array with values between 0 and 1

np.random.rand(4,3)

array([[0.25025917, 0.04778962, 0.084583  ],
       [0.23044254, 0.34438609, 0.2309101 ],
       [0.36496668, 0.69265287, 0.13908988],
       [0.16494901, 0.29533918, 0.73098986]])

####  2.1.2 np.random.randint

Returns random integers from the "discrete uniform" distribution of the specified dtype in the interval. 

Results from this function contains a size shapped array if random integers from the appropriate distribution or a single random int if size not provided.

In [3]:
## Generate a 1 X 10 array with values between 0 and 3 

np.random.randint(3, size=10)

array([0, 1, 2, 2, 2, 2, 2, 2, 2, 1])

####  2.1.3 np.random.random_sample

This function is used to return a array of random floats of shape size. The uniform distribution (continuous) is one of the simplest probability distributions in statistics.

If there is no size specified in the function then a single float will be returned.


In [4]:
## Generate a random single float 

np.random.random_sample()

0.3624600626911477

In [5]:
## Generate a four by five array of random numbers from [-5,0]

5 * np.random.random_sample((4,5)) - 5

array([[-2.58216591, -1.31597236, -0.8449067 , -0.52956975, -1.05689123],
       [-4.47645181, -3.26486873, -0.77337837, -2.55103085, -3.64536568],
       [-4.30538946, -3.7851234 , -1.31453752, -3.82047553, -2.40284278],
       [-4.23628505, -4.43443956, -2.71092014, -1.55153984, -0.74619419]])

### 2.2 - Permutations

A permutation is used to randomly shuffle the elements of an array.  

I have included the function under the "Permutations" section of the numpy.random documentation below


#### 2.2.1 Shuffle

This function is used to modify the sequence in-place by shuffling its contents. If it has to shuffle a multi dimentional array then it will only shuffle the array along the first index of it.



In [6]:
## Generate an array with the given size and shuffle the contents

array = np.arange(10)
np.random.shuffle(array)
array


array([2, 7, 9, 0, 3, 8, 5, 4, 6, 1])

In [7]:
## Generate a multi dimentional array and shuffle the contents

array = np.arange(12).reshape((3,4))
np.random.shuffle(array)
array


array([[ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

#### 2.2.2 Permutation

This function is used to permute a sequence or return a permuted range. If the input value is a multi dimentional array then it will make a copy and shuffle the elements randomly


In [8]:
## Generate a permute sequence

np.random.permutation(10)

array([4, 2, 5, 3, 7, 8, 1, 6, 9, 0])

In [9]:
## Generate a random array from a given array

np.random.permutation([3,6,8,12,20,25])


array([20, 12,  6,  8, 25,  3])

In [12]:
## Generate a random array and shuffle it

array = np.arange(12).reshape(3,4)
np.random.permutation(array)
array


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])